### ISSUE TITLE
Select all 

### ISSUE THREAD

**Issue by edyee** [zgelici/FOS-Streaming-v1#5]
still dont work

**Comment by zgelici** [comment]
its working on my test servers. Can you show it to me?

**Comment by Goldtrak** [comment]
Hi,

Teh issue is in User Client  your can't copy the link ( M3u8 and E2 ).

Best regards

**Comment by Goldtrak** [comment]
@zgelici  here is more detailles:

http://multics.info/threads/fos-streaming-v1.56885/page-4

best regards

**Comment by edyee** [comment]
in streams, there should be a restart button for stream as well ..you have put stop start already just add restart that ll be good

**Comment by edyee** [comment]
in manage transcode file ..instead of fps you put Video bitrate *..please change

**Comment by zgelici** [comment]
Thanks i will fix this in the next update

**Comment by edyee** [comment]
also i have just found another big bug, ffmpeg defaul1 copy profile only work on m3u8 link, not anything else, all other streams works if i create new transcode profile

**Comment by zgelici** [comment]
# i pushed some fixes

Can you send a example to info@tyfix.nl (with your name in the email: edyee). Than we can look at it.

**Comment by edyee** [comment]
sorry was out whole day, i just copy copy command in my ffmpeg, don't use any special thing ...which works fine for my self but i run ffmpeg via command

**Comment by sarelmx** [comment]
Hi nice job, i think that you can put secure token and secure streaming with this bash:

#!/bin/bash

# Be warned!!! there is an "rm -r" at the end of this script.  I do not guarantee anything, in particular that (mis)use won't damage something important.
# Use at your own risk!
# Copyright public domain
# Derived from: http://dryize.wordpress.com/2014/04/02/protected-hls-using-ffmpeg-and-openssl/

set -e     # Exit on errors

keyFile='video.key'
vidFile="$1"
playList='list.m3u8'    # Must end with .m3u8!
splitFilePrefix='4'

# Only run if the video file is readable and is not an irregular file
if [ -f "$vidFile" -a -r "$vidFile" ]; then
# Whole rest of program runs in this if; exits 2 at the end if the above fails.

# If folder exists, add it to our paths
if [ -d "$2" ]; then
outDir="$2"
else    # Try to make the directory
mkdir "$2" || exit 1
outDir="$2"
fi

tempDir="$outDir/.$$_tmp"
keyFile="$outDir/$keyFile"

mkdir $tempDir    # It is deleted later

# Stuff from the original script

openssl rand 16 > $keyFile
# I'm not sure if I have the quoting right on this. If not, try removing the double quotes in the middle.
encryptionKey=`cat $keyFile | hexdump -e '16/1 "%02x"'`

# Here's where I run ffmpeg
ffmpeg -i "$vidFile" -vcodec libx264 -acodec libvo_aacenc -b:v 128k -flags \
-global_header -map 0:0 -map 0:1 -f segment -segment_time 4 -segment_list_size 0 \
-segment_list "$tempDir/$playList" -segment_format mpegts "$tempDir/$splitFilePrefix"%d.ts
# N.B. I question some of those parameters, such as segment_time, but this is not my command.
# I also had to use libfdk_aac instead of libvo_aacenc
# I thought m3u8 playlists needed full URLs, but he doesn't include them.

numberOfTsFiles=`ls "$tempDir/$splitFilePrefix"*.ts | wc -l`

for (( i=1; i<$numberOfTsFiles; i++ ))
do
initializationVector=`printf '%032x' $i`
openssl aes-128-cbc -e -in "$tempDir/$splitFilePrefix"$i.ts \
-out "$outDir/$splitFilePrefix"$i.ts -nosalt -iv $initializationVector -K $encryptionKey
done

# Write something to the middle of the head of the playlist
{
head -4 "$tempDir/$playList"
echo '#EXT-X-KEY:METHOD=AES-128,URI='"$keyFile"
echo '#EXT-X-TARGETDURATION:9'
egrep "$tempDir/$playList" -vie '#EXT-X-TARGETDURATION:' \
| tail -n +5
} > "$outDir/$playList"

# Get rid of the unencrypted files and unmodified playlist
rm -r "$tempDir"

# Close the opening if
else exit 2
fi

**Comment by edyee** [comment]
is this bash for me :)

**Comment by sarelmx** [comment]
ok try included this for the live streaming edyee XD

**Comment by edyee** [comment]
still copy copy dont work on all the streams

**Comment by zgelici** [comment]
@enyee . its working on my server. we need to look at the problem to solve it. can you send a email to info@tyfix.nl or zgelici@gmail.com

**Comment by edyee** [comment]
i gave up with this panel, it can restream only m3u8, nothing else, waisted whole week for waiting

**Comment by plexmediaserver** [comment]
I have everything working is there away to get mpeg-ts hls working as a output file in script it shows hls folder but in directory there is only hl folder help would be appreciated.
